# Generated by Django 2.1.5 on 2019-02-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=100)),
                ('company', models.CharField(choices=[('Xiaomi', 'Xiaomi'), ('Samsumg', 'Samsumg')], default=None, max_length=30)),
            ],
        ),
    ]
