# Generated by Django 2.1.5 on 2019-02-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190206_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledata',
            name='datafile',
            field=models.FileField(upload_to=''),
        ),
    ]
