# Generated by Django 2.1.5 on 2019-02-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190206_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledata',
            name='datafile',
            field=models.FileField(upload_to='Others/'),
        ),
    ]
