# Generated by Django 2.1.5 on 2019-02-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190206_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Mobile')),
            ],
        ),
        migrations.AlterField(
            model_name='mobiledata',
            name='datafile',
            field=models.FileField(upload_to=''),
        ),
    ]
