# Generated by Django 2.1.5 on 2019-02-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190206_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilereviews',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
