# Generated by Django 2.1.5 on 2019-02-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190206_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
