# Generated by Django 2.1.5 on 2019-03-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_mobile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilereviews',
            name='sentiment',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
